// JavaScript Document
DD_belatedPNG.fix('div');
DD_belatedPNG.fix('button');
DD_belatedPNG.fix('a');
DD_belatedPNG.fix('h1');
DD_belatedPNG.fix('h5');
DD_belatedPNG.fix('form');
DD_belatedPNG.fix('p img');
DD_belatedPNG.fix('a img');
DD_belatedPNG.fix('img');
DD_belatedPNG.fix('input');
DD_belatedPNG.fix('li');
DD_belatedPNG.fix('td');
DD_belatedPNG.fix('span');
DD_belatedPNG.fix('table tr td');
DD_belatedPNG.fix('article');
DD_belatedPNG.fix('footer');
DD_belatedPNG.fix('header');
DD_belatedPNG.fix('menu');
DD_belatedPNG.fix('nav');
DD_belatedPNG.fix('section');
DD_belatedPNG.fix('address');
DD_belatedPNG.fix('aside');